import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Pulisci tutto
  await prisma.activityLog.deleteMany();
  await prisma.setting.deleteMany();
  await prisma.maintenance.deleteMany();
  await prisma.order.deleteMany();
  await prisma.trip.deleteMany();
  await prisma.partner.deleteMany();
  await prisma.driver.deleteMany();
  await prisma.vehicle.deleteMany();
  await prisma.company.deleteMany();

  // Crea l'azienda
  const company = await prisma.company.create({
    data: {
      nome: "Trasporti Bianchi Srl",
      indirizzo: "Via Monte Napoleone 22",
      citta: "Milano",
      cap: "20121",
      piva: "IT12345678901",
      telefono: "+39 02 1234567",
      email: "info@trasportibianchi.it",
    },
  });

  console.log("✅ Azienda creata:", company.nome);

  // Crea autisti
  const driversData = [
    {
      nome: "Marco",
      cognome: "Rossi",
      codiceFiscale: "RSSMRC85M15F205X",
      patenteTipo: "CE",
      patenteNumero: "MI12345678",
      patenteScadenza: new Date("2027-06-15"),
      cartaCQC: "CQC001234",
      cqcScadenza: new Date("2027-03-20"),
      tachigrafoScadenza: new Date("2026-08-10"),
      oreGuidaSettimana: 32,
      oreRiposoRimanenti: 11,
      stato: "disponibile" as const,
      telefono: "+39 333 1234567",
      latitudine: 45.4642,
      longitudine: 9.19,
    },
    {
      nome: "Giuseppe",
      cognome: "Colombo",
      codiceFiscale: "CLMGPP78A22F205Y",
      patenteTipo: "CE",
      patenteNumero: "MI23456789",
      patenteScadenza: new Date("2026-03-10"),
      cartaCQC: "CQC002345",
      cqcScadenza: new Date("2026-11-15"),
      tachigrafoScadenza: new Date("2026-04-20"),
      oreGuidaSettimana: 45,
      oreRiposoRimanenti: 9,
      stato: "in_viaggio" as const,
      telefono: "+39 334 2345678",
      latitudine: 45.4384,
      longitudine: 10.9916,
    },
    {
      nome: "Alessandro",
      cognome: "Ferrari",
      codiceFiscale: "FRRLSN90D10F205Z",
      patenteTipo: "C",
      patenteNumero: "TO34567890",
      patenteScadenza: new Date("2028-01-20"),
      cartaCQC: "CQC003456",
      cqcScadenza: new Date("2027-07-10"),
      tachigrafoScadenza: new Date("2027-02-15"),
      oreGuidaSettimana: 18,
      oreRiposoRimanenti: 11,
      stato: "disponibile" as const,
      telefono: "+39 335 3456789",
      latitudine: 45.0703,
      longitudine: 7.6869,
    },
    {
      nome: "Luca",
      cognome: "Esposito",
      codiceFiscale: "SPSLCU82H25F205A",
      patenteTipo: "CE",
      patenteNumero: "BG45678901",
      patenteScadenza: new Date("2027-09-05"),
      cartaCQC: "CQC004567",
      cqcScadenza: new Date("2027-04-30"),
      tachigrafoScadenza: new Date("2026-12-01"),
      oreGuidaSettimana: 50,
      oreRiposoRimanenti: 6,
      stato: "in_viaggio" as const,
      telefono: "+39 336 4567890",
      latitudine: 45.695,
      longitudine: 9.67,
    },
    {
      nome: "Andrea",
      cognome: "Bianchi",
      codiceFiscale: "BNCNDR88L12F205B",
      patenteTipo: "C",
      patenteNumero: "VR56789012",
      patenteScadenza: new Date("2026-05-18"),
      cartaCQC: "CQC005678",
      cqcScadenza: new Date("2026-08-22"),
      tachigrafoScadenza: new Date("2026-06-30"),
      oreGuidaSettimana: 8,
      oreRiposoRimanenti: 11,
      stato: "disponibile" as const,
      telefono: "+39 337 5678901",
      latitudine: 45.4384,
      longitudine: 10.9916,
    },
    {
      nome: "Davide",
      cognome: "Romano",
      codiceFiscale: "RMNDVD92C18F205C",
      patenteTipo: "CE",
      patenteNumero: "PD67890123",
      patenteScadenza: new Date("2028-11-30"),
      cartaCQC: "CQC006789",
      cqcScadenza: new Date("2028-02-14"),
      tachigrafoScadenza: new Date("2027-05-20"),
      oreGuidaSettimana: 0,
      oreRiposoRimanenti: 11,
      stato: "riposo" as const,
      telefono: "+39 338 6789012",
      latitudine: 45.4064,
      longitudine: 11.8768,
    },
    {
      nome: "Simone",
      cognome: "Gallo",
      codiceFiscale: "GLLSMN86F05F205D",
      patenteTipo: "B",
      patenteNumero: "BS78901234",
      patenteScadenza: new Date("2027-02-28"),
      cartaCQC: null,
      cqcScadenza: null,
      tachigrafoScadenza: new Date("2027-01-15"),
      oreGuidaSettimana: 25,
      oreRiposoRimanenti: 11,
      stato: "disponibile" as const,
      telefono: "+39 339 7890123",
      latitudine: 45.5416,
      longitudine: 10.2118,
    },
    {
      nome: "Paolo",
      cognome: "Moretti",
      codiceFiscale: "MRTPLA79B14F205E",
      patenteTipo: "CE",
      patenteNumero: "CO89012345",
      patenteScadenza: new Date("2026-07-22"),
      cartaCQC: "CQC008901",
      cqcScadenza: new Date("2026-10-05"),
      tachigrafoScadenza: new Date("2026-03-15"),
      oreGuidaSettimana: 40,
      oreRiposoRimanenti: 8,
      stato: "non_disponibile" as const,
      telefono: "+39 340 8901234",
      latitudine: 45.808,
      longitudine: 9.0852,
    },
  ];

  const drivers = await Promise.all(
    driversData.map((d) =>
      prisma.driver.create({
        data: { ...d, companyId: company.id },
      })
    )
  );

  console.log(`✅ ${drivers.length} autisti creati`);

  // Crea mezzi
  const vehiclesData = [
    {
      targa: "FN001AB",
      tipo: "furgone" as const,
      marca: "Fiat",
      modello: "Ducato",
      anno: 2022,
      capacitaPesoKg: 1500,
      capacitaVolumeM3: 13,
      consumoKmL: 8.5,
      stato: "disponibile" as const,
      kmAttuali: 45000,
      prossimaRevisione: new Date("2026-06-15"),
    },
    {
      targa: "FN002CD",
      tipo: "camion" as const,
      marca: "Iveco",
      modello: "Eurocargo",
      anno: 2021,
      capacitaPesoKg: 7500,
      capacitaVolumeM3: 40,
      consumoKmL: 4.2,
      stato: "disponibile" as const,
      kmAttuali: 120000,
      prossimaRevisione: new Date("2026-09-20"),
    },
    {
      targa: "FN003EF",
      tipo: "furgone_frigo" as const,
      marca: "Mercedes",
      modello: "Sprinter Frigo",
      anno: 2023,
      capacitaPesoKg: 1200,
      capacitaVolumeM3: 11,
      consumoKmL: 7.8,
      stato: "disponibile" as const,
      kmAttuali: 22000,
      prossimaRevisione: new Date("2027-03-10"),
    },
    {
      targa: "FN004GH",
      tipo: "cisterna" as const,
      marca: "Scania",
      modello: "P320",
      anno: 2020,
      capacitaPesoKg: 15000,
      capacitaVolumeM3: 20,
      consumoKmL: 3.5,
      stato: "in_uso" as const,
      kmAttuali: 180000,
      prossimaRevisione: new Date("2026-04-05"),
    },
    {
      targa: "FN005IJ",
      tipo: "pianale" as const,
      marca: "MAN",
      modello: "TGX",
      anno: 2022,
      capacitaPesoKg: 18000,
      capacitaVolumeM3: 60,
      consumoKmL: 3.2,
      stato: "disponibile" as const,
      kmAttuali: 95000,
      prossimaRevisione: new Date("2026-11-30"),
    },
    {
      targa: "FN006KL",
      tipo: "furgone" as const,
      marca: "Renault",
      modello: "Master",
      anno: 2023,
      capacitaPesoKg: 1800,
      capacitaVolumeM3: 15,
      consumoKmL: 8.0,
      stato: "disponibile" as const,
      kmAttuali: 18000,
      prossimaRevisione: new Date("2027-05-20"),
    },
    {
      targa: "FN007MN",
      tipo: "camion" as const,
      marca: "Iveco",
      modello: "Stralis",
      anno: 2021,
      capacitaPesoKg: 12000,
      capacitaVolumeM3: 55,
      consumoKmL: 3.8,
      stato: "in_uso" as const,
      kmAttuali: 210000,
      prossimaRevisione: new Date("2026-07-15"),
    },
    {
      targa: "FN008OP",
      tipo: "furgone_frigo" as const,
      marca: "Fiat",
      modello: "Ducato Frigo",
      anno: 2022,
      capacitaPesoKg: 1100,
      capacitaVolumeM3: 10,
      consumoKmL: 7.5,
      stato: "manutenzione" as const,
      kmAttuali: 55000,
      prossimaRevisione: new Date("2026-08-10"),
    },
    {
      targa: "FN009QR",
      tipo: "camion" as const,
      marca: "Volvo",
      modello: "FH",
      anno: 2023,
      capacitaPesoKg: 20000,
      capacitaVolumeM3: 70,
      consumoKmL: 3.0,
      stato: "disponibile" as const,
      kmAttuali: 30000,
      prossimaRevisione: new Date("2027-01-25"),
    },
    {
      targa: "FN010ST",
      tipo: "furgone" as const,
      marca: "Volkswagen",
      modello: "Crafter",
      anno: 2024,
      capacitaPesoKg: 1600,
      capacitaVolumeM3: 14,
      consumoKmL: 8.2,
      stato: "disponibile" as const,
      kmAttuali: 8000,
      prossimaRevisione: new Date("2028-02-15"),
    },
    {
      targa: "FN011UV",
      tipo: "pianale" as const,
      marca: "DAF",
      modello: "XF",
      anno: 2021,
      capacitaPesoKg: 16000,
      capacitaVolumeM3: 58,
      consumoKmL: 3.3,
      stato: "disponibile" as const,
      kmAttuali: 145000,
      prossimaRevisione: new Date("2026-05-10"),
    },
    {
      targa: "FN012WX",
      tipo: "cisterna" as const,
      marca: "Mercedes",
      modello: "Actros",
      anno: 2022,
      capacitaPesoKg: 18000,
      capacitaVolumeM3: 25,
      consumoKmL: 3.4,
      stato: "disponibile" as const,
      kmAttuali: 78000,
      prossimaRevisione: new Date("2026-10-20"),
    },
  ];

  const vehicles = await Promise.all(
    vehiclesData.map((v) =>
      prisma.vehicle.create({
        data: { ...v, companyId: company.id },
      })
    )
  );

  console.log(`✅ ${vehicles.length} mezzi creati`);

  // Crea ordini
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const dayAfter = new Date(today);
  dayAfter.setDate(dayAfter.getDate() + 2);

  const ordersData = [
    {
      codiceOrdine: "ORD-2026-001",
      mittenteNome: "Magazzino Centrale Bianchi",
      mittenteIndirizzo: "Via Monte Napoleone 22",
      mittenteCitta: "Milano",
      mittenteCAP: "20121",
      mittenteLat: 45.4685,
      mittenteLng: 9.1954,
      destinatarioNome: "Supermercato Verdi Srl",
      destinatarioIndirizzo: "Via XX Settembre 15",
      destinatarioCitta: "Torino",
      destinatarioCAP: "10121",
      destinatarioLat: 45.0703,
      destinatarioLng: 7.6869,
      tipoMerce: "Alimentari secchi",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 2500,
      volumeM3: 12,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(8, 0)),
      finestraCaricoA: new Date(today.setHours(10, 0)),
      finestraConsegnaDa: new Date(today.setHours(14, 0)),
      finestraConsegnaA: new Date(today.setHours(18, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-002",
      mittenteNome: "Caseificio Lombardo",
      mittenteIndirizzo: "Via Garibaldi 45",
      mittenteCitta: "Brescia",
      mittenteCAP: "25121",
      mittenteLat: 45.5416,
      mittenteLng: 10.2118,
      destinatarioNome: "Ristorante Da Mario",
      destinatarioIndirizzo: "Piazza delle Erbe 3",
      destinatarioCitta: "Verona",
      destinatarioCAP: "37121",
      destinatarioLat: 45.4384,
      destinatarioLng: 10.9916,
      tipoMerce: "Latticini freschi",
      merceRefrigerata: true,
      mercePericolosa: false,
      pesoKg: 800,
      volumeM3: 5,
      urgenza: "urgente" as const,
      finestraCaricoDa: new Date(today.setHours(6, 0)),
      finestraCaricoA: new Date(today.setHours(7, 30)),
      finestraConsegnaDa: new Date(today.setHours(9, 0)),
      finestraConsegnaA: new Date(today.setHours(11, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-003",
      mittenteNome: "Industria Chimica Alfa",
      mittenteIndirizzo: "Zona Industriale Nord 12",
      mittenteCitta: "Bergamo",
      mittenteCAP: "24100",
      mittenteLat: 45.695,
      mittenteLng: 9.67,
      destinatarioNome: "Stabilimento Beta",
      destinatarioIndirizzo: "Via dell'Industria 78",
      destinatarioCitta: "Padova",
      destinatarioCAP: "35100",
      destinatarioLat: 45.4064,
      destinatarioLng: 11.8768,
      tipoMerce: "Prodotti chimici liquidi",
      merceRefrigerata: false,
      mercePericolosa: true,
      pesoKg: 12000,
      volumeM3: 18,
      urgenza: "programmato" as const,
      finestraCaricoDa: new Date(tomorrow.setHours(7, 0)),
      finestraCaricoA: new Date(tomorrow.setHours(9, 0)),
      finestraConsegnaDa: new Date(tomorrow.setHours(13, 0)),
      finestraConsegnaA: new Date(tomorrow.setHours(17, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-004",
      mittenteNome: "Magazzino Centrale Bianchi",
      mittenteIndirizzo: "Via Monte Napoleone 22",
      mittenteCitta: "Milano",
      mittenteCAP: "20121",
      mittenteLat: 45.4685,
      mittenteLng: 9.1954,
      destinatarioNome: "Negozio Tessuti Rossi",
      destinatarioIndirizzo: "Corso Italia 56",
      destinatarioCitta: "Como",
      destinatarioCAP: "22100",
      destinatarioLat: 45.808,
      destinatarioLng: 9.0852,
      tipoMerce: "Tessuti e abbigliamento",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 600,
      volumeM3: 8,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(9, 0)),
      finestraCaricoA: new Date(today.setHours(11, 0)),
      finestraConsegnaDa: new Date(today.setHours(13, 0)),
      finestraConsegnaA: new Date(today.setHours(16, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-005",
      mittenteNome: "Cantina Valpolicella",
      mittenteIndirizzo: "Via del Vino 8",
      mittenteCitta: "Verona",
      mittenteCAP: "37121",
      mittenteLat: 45.4384,
      mittenteLng: 10.9916,
      destinatarioNome: "Enoteca Milano Centro",
      destinatarioIndirizzo: "Via Dante 22",
      destinatarioCitta: "Milano",
      destinatarioCAP: "20121",
      destinatarioLat: 45.4685,
      destinatarioLng: 9.1954,
      tipoMerce: "Vini in bottiglia",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 3200,
      volumeM3: 6,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(7, 0)),
      finestraCaricoA: new Date(today.setHours(9, 0)),
      finestraConsegnaDa: new Date(today.setHours(12, 0)),
      finestraConsegnaA: new Date(today.setHours(15, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-006",
      mittenteNome: "Acciaieria Piemonte",
      mittenteIndirizzo: "Strada Statale 35, km 12",
      mittenteCitta: "Novara",
      mittenteCAP: "28100",
      mittenteLat: 45.4494,
      mittenteLng: 8.622,
      destinatarioNome: "Officina Meccanica Trentina",
      destinatarioIndirizzo: "Via Brennero 150",
      destinatarioCitta: "Trento",
      destinatarioCAP: "38121",
      destinatarioLat: 46.0748,
      destinatarioLng: 11.1217,
      tipoMerce: "Profili in acciaio",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 15000,
      volumeM3: 45,
      urgenza: "programmato" as const,
      finestraCaricoDa: new Date(tomorrow.setHours(6, 0)),
      finestraCaricoA: new Date(tomorrow.setHours(8, 0)),
      finestraConsegnaDa: new Date(tomorrow.setHours(12, 0)),
      finestraConsegnaA: new Date(tomorrow.setHours(16, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-007",
      mittenteNome: "Farmaceutica Veneta",
      mittenteIndirizzo: "Via Padana 200",
      mittenteCitta: "Vicenza",
      mittenteCAP: "36100",
      mittenteLat: 45.5455,
      mittenteLng: 11.5354,
      destinatarioNome: "Ospedale Niguarda",
      destinatarioIndirizzo: "Piazza Ospedale Maggiore 3",
      destinatarioCitta: "Milano",
      destinatarioCAP: "20162",
      destinatarioLat: 45.5064,
      destinatarioLng: 9.1857,
      tipoMerce: "Farmaci temperatura controllata",
      merceRefrigerata: true,
      mercePericolosa: false,
      pesoKg: 400,
      volumeM3: 3,
      urgenza: "urgente" as const,
      finestraCaricoDa: new Date(today.setHours(5, 0)),
      finestraCaricoA: new Date(today.setHours(6, 30)),
      finestraConsegnaDa: new Date(today.setHours(8, 0)),
      finestraConsegnaA: new Date(today.setHours(10, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-008",
      mittenteNome: "Magazzino Centrale Bianchi",
      mittenteIndirizzo: "Via Monte Napoleone 22",
      mittenteCitta: "Milano",
      mittenteCAP: "20121",
      mittenteLat: 45.4685,
      mittenteLng: 9.1954,
      destinatarioNome: "Centro Commerciale Orio",
      destinatarioIndirizzo: "Via Portico 71",
      destinatarioCitta: "Orio al Serio",
      destinatarioCAP: "24050",
      destinatarioLat: 45.6679,
      destinatarioLng: 9.6962,
      tipoMerce: "Elettronica di consumo",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 1800,
      volumeM3: 10,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(8, 0)),
      finestraCaricoA: new Date(today.setHours(10, 0)),
      finestraConsegnaDa: new Date(today.setHours(14, 0)),
      finestraConsegnaA: new Date(today.setHours(17, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-009",
      mittenteNome: "Cooperativa Agricola Mantovana",
      mittenteIndirizzo: "Via Verdi 34",
      mittenteCitta: "Mantova",
      mittenteCAP: "46100",
      mittenteLat: 45.1564,
      mittenteLng: 10.7914,
      destinatarioNome: "Mercato Ortofrutticolo",
      destinatarioIndirizzo: "Via Sammartini 71",
      destinatarioCitta: "Milano",
      destinatarioCAP: "20125",
      destinatarioLat: 45.4862,
      destinatarioLng: 9.2022,
      tipoMerce: "Frutta e verdura fresca",
      merceRefrigerata: true,
      mercePericolosa: false,
      pesoKg: 5000,
      volumeM3: 25,
      urgenza: "urgente" as const,
      finestraCaricoDa: new Date(today.setHours(4, 0)),
      finestraCaricoA: new Date(today.setHours(5, 30)),
      finestraConsegnaDa: new Date(today.setHours(7, 0)),
      finestraConsegnaA: new Date(today.setHours(9, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-010",
      mittenteNome: "Mobilificio Brianza",
      mittenteIndirizzo: "Via Monza 88",
      mittenteCitta: "Lissone",
      mittenteCAP: "20851",
      mittenteLat: 45.6132,
      mittenteLng: 9.2432,
      destinatarioNome: "Arredamenti Lago",
      destinatarioIndirizzo: "Lungolago Zanardelli 45",
      destinatarioCitta: "Desenzano del Garda",
      destinatarioCAP: "25015",
      destinatarioLat: 45.4719,
      destinatarioLng: 10.5368,
      tipoMerce: "Mobili e arredi",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 2200,
      volumeM3: 35,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(tomorrow.setHours(8, 0)),
      finestraCaricoA: new Date(tomorrow.setHours(10, 0)),
      finestraConsegnaDa: new Date(tomorrow.setHours(14, 0)),
      finestraConsegnaA: new Date(tomorrow.setHours(17, 0)),
      stato: "pending" as const,
    },
    // Ordini già completati/assegnati per storico
    {
      codiceOrdine: "ORD-2026-011",
      mittenteNome: "Magazzino Centrale Bianchi",
      mittenteIndirizzo: "Via Monte Napoleone 22",
      mittenteCitta: "Milano",
      mittenteCAP: "20121",
      mittenteLat: 45.4685,
      mittenteLng: 9.1954,
      destinatarioNome: "Ferramenta Genovese",
      destinatarioIndirizzo: "Via San Lorenzo 20",
      destinatarioCitta: "Genova",
      destinatarioCAP: "16123",
      destinatarioLat: 44.4056,
      destinatarioLng: 8.9463,
      tipoMerce: "Ferramenta e utensili",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 3500,
      volumeM3: 18,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(7, 0)),
      finestraCaricoA: new Date(today.setHours(9, 0)),
      finestraConsegnaDa: new Date(today.setHours(13, 0)),
      finestraConsegnaA: new Date(today.setHours(17, 0)),
      stato: "in_corso" as const,
    },
    {
      codiceOrdine: "ORD-2026-012",
      mittenteNome: "Tipografia Milanese",
      mittenteIndirizzo: "Viale Certosa 120",
      mittenteCitta: "Milano",
      mittenteCAP: "20151",
      mittenteLat: 45.4928,
      mittenteLng: 9.1342,
      destinatarioNome: "Libreria Feltrinelli",
      destinatarioIndirizzo: "Piazza Duomo 1",
      destinatarioCitta: "Milano",
      destinatarioCAP: "20122",
      destinatarioLat: 45.4641,
      destinatarioLng: 9.1919,
      tipoMerce: "Libri e stampati",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 500,
      volumeM3: 4,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(10, 0)),
      finestraCaricoA: new Date(today.setHours(11, 0)),
      finestraConsegnaDa: new Date(today.setHours(14, 0)),
      finestraConsegnaA: new Date(today.setHours(16, 0)),
      stato: "completato" as const,
    },
    {
      codiceOrdine: "ORD-2026-013",
      mittenteNome: "Oleificio Gardesano",
      mittenteIndirizzo: "Via Lago 5",
      mittenteCitta: "Bardolino",
      mittenteCAP: "37011",
      mittenteLat: 45.5491,
      mittenteLng: 10.7227,
      destinatarioNome: "Eataly Torino",
      destinatarioIndirizzo: "Via Nizza 230",
      destinatarioCitta: "Torino",
      destinatarioCAP: "10126",
      destinatarioLat: 45.0415,
      destinatarioLng: 7.6759,
      tipoMerce: "Olio d'oliva",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 1200,
      volumeM3: 3,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(today.setHours(8, 0)),
      finestraCaricoA: new Date(today.setHours(10, 0)),
      finestraConsegnaDa: new Date(today.setHours(15, 0)),
      finestraConsegnaA: new Date(today.setHours(18, 0)),
      stato: "completato" as const,
    },
    {
      codiceOrdine: "ORD-2026-014",
      mittenteNome: "Cartiera del Piave",
      mittenteIndirizzo: "Via Feltrina 234",
      mittenteCitta: "Treviso",
      mittenteCAP: "31100",
      mittenteLat: 45.672,
      mittenteLng: 12.2424,
      destinatarioNome: "Cartoleria Bresciana",
      destinatarioIndirizzo: "Corso Zanardelli 10",
      destinatarioCitta: "Brescia",
      destinatarioCAP: "25121",
      destinatarioLat: 45.5394,
      destinatarioLng: 10.2175,
      tipoMerce: "Carta e cartone",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 8000,
      volumeM3: 35,
      urgenza: "programmato" as const,
      finestraCaricoDa: new Date(dayAfter.setHours(7, 0)),
      finestraCaricoA: new Date(dayAfter.setHours(9, 0)),
      finestraConsegnaDa: new Date(dayAfter.setHours(14, 0)),
      finestraConsegnaA: new Date(dayAfter.setHours(18, 0)),
      stato: "pending" as const,
    },
    {
      codiceOrdine: "ORD-2026-015",
      mittenteNome: "Conceria Veneta",
      mittenteIndirizzo: "Via Conciaria 67",
      mittenteCitta: "Arzignano",
      mittenteCAP: "36071",
      mittenteLat: 45.5205,
      mittenteLng: 11.3337,
      destinatarioNome: "Pelletteria Fiorentina Outlet",
      destinatarioIndirizzo: "Via della Moda 1",
      destinatarioCitta: "Serravalle Scrivia",
      destinatarioCAP: "15069",
      destinatarioLat: 44.7238,
      destinatarioLng: 8.8558,
      tipoMerce: "Pellami lavorati",
      merceRefrigerata: false,
      mercePericolosa: false,
      pesoKg: 1500,
      volumeM3: 8,
      urgenza: "normale" as const,
      finestraCaricoDa: new Date(tomorrow.setHours(9, 0)),
      finestraCaricoA: new Date(tomorrow.setHours(11, 0)),
      finestraConsegnaDa: new Date(tomorrow.setHours(15, 0)),
      finestraConsegnaA: new Date(tomorrow.setHours(18, 0)),
      stato: "pending" as const,
    },
  ];

  const orders = await Promise.all(
    ordersData.map((o) =>
      prisma.order.create({
        data: { ...o, companyId: company.id },
      })
    )
  );

  console.log(`✅ ${orders.length} ordini creati`);

  // Crea partner
  const partnersData = [
    {
      nome: "Logistica Padana Srl",
      piva: "IT98765432101",
      indirizzo: "Via Emilia 156",
      citta: "Piacenza",
      telefono: "+39 0523 123456",
      email: "info@logisticapadana.it",
      zoneOperative: ["Emilia-Romagna", "Lombardia"],
      tipiVeicoli: ["camion", "furgone"],
      costoPerKm: 1.45,
      rating: 4.2,
      noteCollaborazione: "Affidabili per tratte pianura padana. Tempi rispettati nel 95% dei casi.",
    },
    {
      nome: "Trans Alpine Express",
      piva: "IT11223344556",
      indirizzo: "Via Brennero 88",
      citta: "Bolzano",
      telefono: "+39 0471 234567",
      email: "dispatch@transalpine.it",
      zoneOperative: ["Trentino-Alto Adige", "Veneto", "Austria"],
      tipiVeicoli: ["camion", "pianale", "cisterna"],
      costoPerKm: 1.85,
      rating: 4.7,
      noteCollaborazione: "Specializzati trasporti alpini e transfrontalieri. Premium ma affidabili.",
    },
    {
      nome: "Veloce Trasporti Piemonte",
      piva: "IT99887766554",
      indirizzo: "Corso Francia 200",
      citta: "Torino",
      telefono: "+39 011 345678",
      email: "ops@velocetrasporti.it",
      zoneOperative: ["Piemonte", "Liguria", "Valle d'Aosta"],
      tipiVeicoli: ["furgone", "furgone_frigo", "camion"],
      costoPerKm: 1.35,
      rating: 3.9,
      noteCollaborazione: "Buon rapporto qualità-prezzo per consegne regionali.",
    },
    {
      nome: "Frigor Express Italia",
      piva: "IT44556677889",
      indirizzo: "Via Frigoriferi 12",
      citta: "Parma",
      telefono: "+39 0521 456789",
      email: "cold@frigorexpress.it",
      zoneOperative: ["Lombardia", "Emilia-Romagna", "Veneto", "Toscana"],
      tipiVeicoli: ["furgone_frigo", "camion"],
      costoPerKm: 2.1,
      rating: 4.5,
      noteCollaborazione: "Specialisti catena del freddo. Certificati HACCP e ATP.",
    },
  ];

  const partners = await Promise.all(
    partnersData.map((p) =>
      prisma.partner.create({
        data: { ...p, companyId: company.id },
      })
    )
  );

  console.log(`✅ ${partners.length} partner creati`);

  // Crea manutenzioni
  const maintenancesData = [
    {
      vehicleId: vehicles[0].id,
      tipo: "ordinaria",
      descrizione: "Cambio olio e filtri",
      costo: 350,
      data: new Date("2026-01-15"),
      kmAlMomento: 42000,
    },
    {
      vehicleId: vehicles[1].id,
      tipo: "revisione",
      descrizione: "Revisione annuale",
      costo: 800,
      data: new Date("2025-12-10"),
      kmAlMomento: 115000,
    },
    {
      vehicleId: vehicles[7].id,
      tipo: "straordinaria",
      descrizione: "Riparazione impianto refrigerazione",
      costo: 2500,
      data: new Date("2026-02-16"),
      kmAlMomento: 55000,
    },
    {
      vehicleId: vehicles[3].id,
      tipo: "ordinaria",
      descrizione: "Sostituzione pneumatici",
      costo: 1800,
      data: new Date("2026-02-01"),
      kmAlMomento: 175000,
    },
  ];

  await Promise.all(
    maintenancesData.map((m) => prisma.maintenance.create({ data: m }))
  );

  console.log("✅ Manutenzioni create");

  // Crea settings
  await prisma.setting.createMany({
    data: [
      {
        companyId: company.id,
        chiave: "anthropic_api_key",
        valore: "",
      },
      {
        companyId: company.id,
        chiave: "ors_api_key",
        valore: "",
      },
      {
        companyId: company.id,
        chiave: "costo_carburante_litro",
        valore: "1.85",
      },
      {
        companyId: company.id,
        chiave: "piano_abbonamento",
        valore: "professional",
      },
    ],
  });

  console.log("✅ Settings creati");

  // Crea activity log
  const logs = [
    {
      companyId: company.id,
      tipo: "order_created",
      messaggio: "Nuovo ordine ORD-2026-012 creato per Libreria Feltrinelli",
      createdAt: new Date(Date.now() - 3600000 * 5),
    },
    {
      companyId: company.id,
      tipo: "trip_completed",
      messaggio: "Tratta Milano → Genova completata da G. Colombo",
      createdAt: new Date(Date.now() - 3600000 * 4),
    },
    {
      companyId: company.id,
      tipo: "driver_status",
      messaggio: "Autista D. Romano in riposo obbligatorio",
      createdAt: new Date(Date.now() - 3600000 * 3),
    },
    {
      companyId: company.id,
      tipo: "vehicle_maintenance",
      messaggio: "Mezzo FN008OP in manutenzione - riparazione frigo",
      createdAt: new Date(Date.now() - 3600000 * 2),
    },
    {
      companyId: company.id,
      tipo: "order_created",
      messaggio: "Nuovo ordine urgente ORD-2026-007 - Farmaci per Ospedale Niguarda",
      createdAt: new Date(Date.now() - 3600000 * 1),
    },
    {
      companyId: company.id,
      tipo: "ai_dispatch",
      messaggio: "Piano AI generato: 5 tratte ottimizzate, risparmio stimato 12% km",
      createdAt: new Date(Date.now() - 1800000),
    },
  ];

  await prisma.activityLog.createMany({ data: logs });

  console.log("✅ Activity log creati");
  console.log("\n🎉 Seed completato con successo!");
  console.log(`   Azienda: ${company.nome}`);
  console.log(`   Autisti: ${drivers.length}`);
  console.log(`   Mezzi: ${vehicles.length}`);
  console.log(`   Ordini: ${orders.length}`);
  console.log(`   Partner: ${partners.length}`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
